// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEvDHuB-AvyAGhwV7--y6U1yK-ip9kwc',
    appId: '1:90938156414:web:a48b83aa4b173673767f2f',
    messagingSenderId: '90938156414',
    projectId: 'stress-and-gpa-prediction',
    authDomain: 'stress-and-gpa-prediction.firebaseapp.com',
    storageBucket: 'stress-and-gpa-prediction.firebasestorage.app',
    measurementId: 'G-E0FZZ5PQ2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApARyYW2PtRpt_EXO1XhQDofI5Oe45KxE',
    appId: '1:90938156414:android:2ab6ff04a0fcbac9767f2f',
    messagingSenderId: '90938156414',
    projectId: 'stress-and-gpa-prediction',
    storageBucket: 'stress-and-gpa-prediction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOMu_kwdMNyhf3hjZCJroin5LcPSOLuU',
    appId: '1:90938156414:ios:f477844eaf4897b9767f2f',
    messagingSenderId: '90938156414',
    projectId: 'stress-and-gpa-prediction',
    storageBucket: 'stress-and-gpa-prediction.firebasestorage.app',
    iosBundleId: 'com.example.stressDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXOMu_kwdMNyhf3hjZCJroin5LcPSOLuU',
    appId: '1:90938156414:ios:f477844eaf4897b9767f2f',
    messagingSenderId: '90938156414',
    projectId: 'stress-and-gpa-prediction',
    storageBucket: 'stress-and-gpa-prediction.firebasestorage.app',
    iosBundleId: 'com.example.stressDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEvDHuB-AvyAGhwV7--y6U1yK-ip9kwc',
    appId: '1:90938156414:web:a639a686acc64e32767f2f',
    messagingSenderId: '90938156414',
    projectId: 'stress-and-gpa-prediction',
    authDomain: 'stress-and-gpa-prediction.firebaseapp.com',
    storageBucket: 'stress-and-gpa-prediction.firebasestorage.app',
    measurementId: 'G-7WRT3GG1MV',
  );
}
