name: health
description: Wrapper for Apple's HealthKit on iOS and Google's Health Connect on Android.
version: 12.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
#  intl: '>=0.18.0 <0.21.0'
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  fl_chart: ^0.70.2
  flutter_animate: ^4.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  smooth_page_indicator: ^1.2.1
  device_info_plus: '>=9.0.0 <12.0.0'
  json_annotation: ^4.8.0
  carp_serializable: ^2.0.0 # polymorphic json serialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any

  # Using carp_serializable & json_serializable to auto generate json code (.g files) with this command:
  #   dart run build_runner build --delete-conflicting-outputs
  build_runner: any
  json_serializable: any
  mocktail: ^1.0.4
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
